# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/vitis_design_icn_ctrl_2_0.xci
# IP: The module: 'vitis_design_icn_ctrl_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/bd_93ee.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_0/bd_93ee_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_1/bd_93ee_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_2/bd_93ee_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_3/bd_93ee_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_4/bd_93ee_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_5/bd_93ee_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_6/bd_93ee_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_7/bd_93ee_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_8/bd_93ee_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_9/bd_93ee_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_10/bd_93ee_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_11/bd_93ee_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_12/bd_93ee_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_1/bd_93ee_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_1/bd_93ee_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_5/bd_93ee_s00a2s_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_6/bd_93ee_sarn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_7/bd_93ee_srn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_8/bd_93ee_sawn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_9/bd_93ee_swn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_10/bd_93ee_sbn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_11/bd_93ee_m00s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_icn_ctrl_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/vitis_design_icn_ctrl_2_0.xci
# IP: The module: 'vitis_design_icn_ctrl_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/bd_93ee.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_0/bd_93ee_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_1/bd_93ee_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_2/bd_93ee_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_3/bd_93ee_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_4/bd_93ee_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_5/bd_93ee_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_6/bd_93ee_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_7/bd_93ee_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_8/bd_93ee_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_9/bd_93ee_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_10/bd_93ee_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_11/bd_93ee_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_12/bd_93ee_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_1/bd_93ee_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_1/bd_93ee_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_5/bd_93ee_s00a2s_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_6/bd_93ee_sarn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_7/bd_93ee_srn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_8/bd_93ee_sawn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_9/bd_93ee_swn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_10/bd_93ee_sbn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_11/bd_93ee_m00s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_icn_ctrl_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
