# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/output/vitis_design_ooc_copy.xdc

# Block Designs: bd/vitis_design/vitis_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design || ORIG_REF_NAME==vitis_design} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_CIPS_0_0/vitis_design_CIPS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_CIPS_0_0 || ORIG_REF_NAME==vitis_design_CIPS_0_0} -quiet] -quiet

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/bd_57a1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_57a1 || ORIG_REF_NAME==bd_57a1} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/ip/ip_0/bd_57a1_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_57a1_pspmc_0_0 || ORIG_REF_NAME==bd_57a1_pspmc_0_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_cips_noc_0 || ORIG_REF_NAME==vitis_design_cips_noc_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_noc_ddr4_0/vitis_design_noc_ddr4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_noc_ddr4_0 || ORIG_REF_NAME==vitis_design_noc_ddr4_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_noc_lpddr4_0 || ORIG_REF_NAME==vitis_design_noc_lpddr4_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_ai_engine_0_0/vitis_design_ai_engine_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_ai_engine_0_0 || ORIG_REF_NAME==vitis_design_ai_engine_0_0} -quiet] -quiet

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_ai_engine_0_0/bd_0/bd_05a5.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_05a5 || ORIG_REF_NAME==bd_05a5} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_ai_engine_0_0/bd_0/ip/ip_0/bd_05a5_noc_ai_mm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_05a5_noc_ai_mm_0_0 || ORIG_REF_NAME==bd_05a5_noc_ai_mm_0_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_intc_cascaded_1_0/vitis_design_axi_intc_cascaded_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_intc_cascaded_1_0 || ORIG_REF_NAME==vitis_design_axi_intc_cascaded_1_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_intc_parent_0/vitis_design_axi_intc_parent_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_intc_parent_0 || ORIG_REF_NAME==vitis_design_axi_intc_parent_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_xlconcat_0_0/vitis_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_xlconcat_0_0 || ORIG_REF_NAME==vitis_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_clk_wizard_0_0/vitis_design_clk_wizard_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_clk_wizard_0_0 || ORIG_REF_NAME==vitis_design_clk_wizard_0_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_psr_104mhz_0/vitis_design_psr_104mhz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_psr_104mhz_0 || ORIG_REF_NAME==vitis_design_psr_104mhz_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_psr_156mhz_0/vitis_design_psr_156mhz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_psr_156mhz_0 || ORIG_REF_NAME==vitis_design_psr_156mhz_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_psr_312mhz_0/vitis_design_psr_312mhz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_psr_312mhz_0 || ORIG_REF_NAME==vitis_design_psr_312mhz_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_psr_78mhz_0/vitis_design_psr_78mhz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_psr_78mhz_0 || ORIG_REF_NAME==vitis_design_psr_78mhz_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_psr_208mhz_0/vitis_design_psr_208mhz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_psr_208mhz_0 || ORIG_REF_NAME==vitis_design_psr_208mhz_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_psr_416mhz_0/vitis_design_psr_416mhz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_psr_416mhz_0 || ORIG_REF_NAME==vitis_design_psr_416mhz_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_psr_625mhz_0/vitis_design_psr_625mhz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_psr_625mhz_0 || ORIG_REF_NAME==vitis_design_psr_625mhz_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/vitis_design_icn_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_icn_ctrl_1_0 || ORIG_REF_NAME==vitis_design_icn_ctrl_1_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/vitis_design_icn_ctrl_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_icn_ctrl_2_0 || ORIG_REF_NAME==vitis_design_icn_ctrl_2_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_dummy_slave_0_0/vitis_design_dummy_slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_dummy_slave_0_0 || ORIG_REF_NAME==vitis_design_dummy_slave_0_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_dummy_slave_1_0/vitis_design_dummy_slave_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_dummy_slave_1_0 || ORIG_REF_NAME==vitis_design_dummy_slave_1_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_dummy_slave_2_0/vitis_design_dummy_slave_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_dummy_slave_2_0 || ORIG_REF_NAME==vitis_design_dummy_slave_2_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_dummy_slave_3_0/vitis_design_dummy_slave_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_dummy_slave_3_0 || ORIG_REF_NAME==vitis_design_dummy_slave_3_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/vitis_design_icn_ctrl_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_icn_ctrl_3_0 || ORIG_REF_NAME==vitis_design_icn_ctrl_3_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/vitis_design_icn_ctrl_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_icn_ctrl_4_0 || ORIG_REF_NAME==vitis_design_icn_ctrl_4_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/vitis_design_icn_ctrl_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_icn_ctrl_5_0 || ORIG_REF_NAME==vitis_design_icn_ctrl_5_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_mac_1_0/vitis_design_mac_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_mac_1_0 || ORIG_REF_NAME==vitis_design_mac_1_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_intc_cascaded_1_intr_1_interrupt_concat_0/vitis_design_axi_intc_cascaded_1_intr_1_interrupt_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_intc_cascaded_1_intr_1_interrupt_concat_0 || ORIG_REF_NAME==vitis_design_axi_intc_cascaded_1_intr_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_irq_const_tieoff_0/vitis_design_irq_const_tieoff_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_irq_const_tieoff_0 || ORIG_REF_NAME==vitis_design_irq_const_tieoff_0} -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/ip/ip_0/bd_57a1_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_57a1_pspmc_0_0 || ORIG_REF_NAME==bd_57a1_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/ip/ip_0/pspmc_v1_3/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_57a1_pspmc_0_0 || ORIG_REF_NAME==bd_57a1_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/bd_57a1_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_ai_engine_0_0/bd_0/bd_05a5_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/vitis_design_ooc.xdc
