# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.runs/synth_1/vitis_design_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param project.loadTopLevelOOCConstrs 1
set_param project.enablePRFlowIPI 1
set_param bd.ForceAppCoreUpgrade 1
set_param bd.debug_profile.script /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/.local/debug_profile_automation.tcl
set_param compiler.enablePerformanceTrace 1
set_param hd.Visual 0
set_param project.gatelevelSubdesign 1
set_param bd.enable_dpa 1
set_param place.ultrathreadsUsed 0
set_param general.maxThreads 1
set_param chipscope.flow 0
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcvc1902-vsva2197-2MP-e-S
set_property tool_flow SDx [current_project]

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.cache/wt [current_project]
set_property parent.project_path /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/.local/hw_platform/board} [current_project]
set_property board_part xilinx.com:vck190:part0:3.2 [current_project]
set_property ip_repo_paths {
  /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/int/xo/ip_repo/xilinx_com_hls_mac_1_0
  /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/.local/hw_platform/ipcache
  /tools/Xilinx/Vitis/2023.1/data/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/ubuntu/Desktop/dsp_recon/system_project/.ipcache [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/imports/nsln/nocattrs.dat
  /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/common/nsln/nocattrs.dat
}
read_verilog -library xil_defaultlib /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/hdl/vitis_design_wrapper.v
add_files /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/vitis_design.bd
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/ip/ip_0/bd_57a1_pspmc_0_0.xdc]
set_property used_in_synthesis false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/ip/ip_0/pspmc_v1_3/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/ip/ip_0/pspmc_v1_3/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_CIPS_0_0/bd_0/bd_57a1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_0/xdc/bd_27ec_S07_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_2/xdc/bd_27ec_S04_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_3/xdc/bd_27ec_S03_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_4/xdc/bd_27ec_S06_AXI_rpu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_5/xdc/bd_27ec_S02_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_6/xdc/bd_27ec_S05_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_7/xdc/bd_27ec_S01_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_8/xdc/bd_27ec_S00_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_9/xdc/bd_27ec_M00_AXI_nsu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_ddr4_0/bd_0/ip/ip_0/xdc/bd_90d1_S00_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_ddr4_0/bd_0/ip/ip_2/hdl/par/bd_90d1_MC0_ddrc_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_ddr4_0/vitis_design_noc_ddr4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_ddr4_0/vitis_design_noc_ddr4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_ddr4_0/vitis_design_noc_ddr4_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_0/hdl/par/bd_28ba_MC1_ddrc_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_1/hdl/par/bd_28ba_MC0_ddrc_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_ai_engine_0_0/bd_0/bd_05a5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_intc_cascaded_1_0/vitis_design_axi_intc_cascaded_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_intc_cascaded_1_0/vitis_design_axi_intc_cascaded_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_intc_cascaded_1_0/vitis_design_axi_intc_cascaded_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_intc_parent_0/vitis_design_axi_intc_parent_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_intc_parent_0/vitis_design_axi_intc_parent_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_intc_parent_0/vitis_design_axi_intc_parent_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_clk_wizard_0_0/vitis_design_clk_wizard_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_clk_wizard_0_0/vitis_design_clk_wizard_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_clk_wizard_0_0/vitis_design_clk_wizard_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_104mhz_0/vitis_design_psr_104mhz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_104mhz_0/vitis_design_psr_104mhz_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_104mhz_0/vitis_design_psr_104mhz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_156mhz_0/vitis_design_psr_156mhz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_156mhz_0/vitis_design_psr_156mhz_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_156mhz_0/vitis_design_psr_156mhz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_312mhz_0/vitis_design_psr_312mhz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_312mhz_0/vitis_design_psr_312mhz_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_312mhz_0/vitis_design_psr_312mhz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_78mhz_0/vitis_design_psr_78mhz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_78mhz_0/vitis_design_psr_78mhz_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_78mhz_0/vitis_design_psr_78mhz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_208mhz_0/vitis_design_psr_208mhz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_208mhz_0/vitis_design_psr_208mhz_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_208mhz_0/vitis_design_psr_208mhz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_416mhz_0/vitis_design_psr_416mhz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_416mhz_0/vitis_design_psr_416mhz_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_416mhz_0/vitis_design_psr_416mhz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_625mhz_0/vitis_design_psr_625mhz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_625mhz_0/vitis_design_psr_625mhz_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_psr_625mhz_0/vitis_design_psr_625mhz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_1/bd_931e_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_1/bd_931e_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_2/bd_931e_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_2/bd_931e_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_3/bd_931e_psr_aclk2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_3/bd_931e_psr_aclk2_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_4/bd_931e_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_5/bd_931e_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_6/bd_931e_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_7/bd_931e_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_8/bd_931e_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_9/bd_931e_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_10/bd_931e_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_11/bd_931e_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_12/bd_931e_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_13/bd_931e_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_14/bd_931e_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_15/bd_931e_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_16/bd_931e_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_17/bd_931e_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_18/bd_931e_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_22/bd_931e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_23/bd_931e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_24/bd_931e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_25/bd_931e_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_26/bd_931e_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_27/bd_931e_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_28/bd_931e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_29/bd_931e_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_30/bd_931e_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_31/bd_931e_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_32/bd_931e_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_33/bd_931e_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_35/bd_931e_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_36/bd_931e_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_37/bd_931e_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_38/bd_931e_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_39/bd_931e_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_40/bd_931e_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_42/bd_931e_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_43/bd_931e_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_44/bd_931e_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_45/bd_931e_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_46/bd_931e_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_47/bd_931e_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_49/bd_931e_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_50/bd_931e_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_51/bd_931e_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_52/bd_931e_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_53/bd_931e_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_54/bd_931e_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_56/bd_931e_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_57/bd_931e_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_58/bd_931e_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_59/bd_931e_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_60/bd_931e_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_61/bd_931e_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_63/bd_931e_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_64/bd_931e_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_65/bd_931e_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_66/bd_931e_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_67/bd_931e_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_68/bd_931e_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_70/bd_931e_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_71/bd_931e_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_72/bd_931e_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_73/bd_931e_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_74/bd_931e_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_75/bd_931e_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_1/bd_93ee_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_1/bd_93ee_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_5/bd_93ee_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_6/bd_93ee_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_7/bd_93ee_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_8/bd_93ee_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_9/bd_93ee_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_10/bd_93ee_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/bd_0/ip/ip_11/bd_93ee_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_2_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_dummy_slave_0_0/vitis_design_dummy_slave_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_dummy_slave_1_0/vitis_design_dummy_slave_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_dummy_slave_2_0/vitis_design_dummy_slave_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_dummy_slave_3_0/vitis_design_dummy_slave_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/bd_0/ip/ip_1/bd_53bf_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/bd_0/ip/ip_1/bd_53bf_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/bd_0/ip/ip_5/bd_53bf_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/bd_0/ip/ip_6/bd_53bf_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/bd_0/ip/ip_7/bd_53bf_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/bd_0/ip/ip_8/bd_53bf_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/bd_0/ip/ip_9/bd_53bf_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/bd_0/ip/ip_10/bd_53bf_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/bd_0/ip/ip_11/bd_53bf_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_3_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/bd_0/ip/ip_1/bd_920e_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/bd_0/ip/ip_1/bd_920e_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/bd_0/ip/ip_5/bd_920e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/bd_0/ip/ip_6/bd_920e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/bd_0/ip/ip_7/bd_920e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/bd_0/ip/ip_8/bd_920e_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/bd_0/ip/ip_9/bd_920e_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/bd_0/ip/ip_10/bd_920e_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/bd_0/ip/ip_11/bd_920e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_4_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/bd_0/ip/ip_1/bd_525f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/bd_0/ip/ip_1/bd_525f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/bd_0/ip/ip_5/bd_525f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/bd_0/ip/ip_6/bd_525f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/bd_0/ip/ip_7/bd_525f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/bd_0/ip/ip_8/bd_525f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/bd_0/ip/ip_9/bd_525f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/bd_0/ip/ip_10/bd_525f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/bd_0/ip/ip_11/bd_525f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_5_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_mac_1_0/constraints/mac_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/vitis_design_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_ddr4_0/bd_0/ip/ip_2/ip_0/bd_90d1_MC0_ddrc_0_phy_ddrmc.elf]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_0/ip_0/bd_28ba_MC1_ddrc_0_phy_ddrmc.elf]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_1/ip_0/bd_28ba_MC0_ddrc_0_phy_ddrmc.elf]
set_property used_in_synthesis false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/nsln/vitis_design.nts]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/nsln/vitis_design.nts]
set_property used_in_synthesis false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/nsln/vitis_design.ncr]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/nsln/vitis_design.ncr]
set_property used_in_implementation false [get_files -all /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/vitis_design.aieprj]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/output/vitis_design_ooc_copy.xdc
set_property used_in_implementation false [get_files /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/output/vitis_design_ooc_copy.xdc]
set_property processing_order EARLY [get_files /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/output/vitis_design_ooc_copy.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top vitis_design_wrapper -part xcvc1902-vsva2197-2MP-e-S
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vitis_design_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
