# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/vitis_design_icn_ctrl_1_0.xci
# IP: The module: 'vitis_design_icn_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/bd_931e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_0/bd_931e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_1/bd_931e_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_2/bd_931e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_3/bd_931e_psr_aclk2_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_4/bd_931e_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_5/bd_931e_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_6/bd_931e_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_7/bd_931e_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_8/bd_931e_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_9/bd_931e_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_10/bd_931e_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_11/bd_931e_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_12/bd_931e_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_13/bd_931e_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_14/bd_931e_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_15/bd_931e_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_16/bd_931e_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_17/bd_931e_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_18/bd_931e_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_19/bd_931e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_20/bd_931e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_21/bd_931e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_22/bd_931e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_23/bd_931e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_24/bd_931e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_25/bd_931e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_26/bd_931e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_27/bd_931e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_28/bd_931e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_29/bd_931e_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_30/bd_931e_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_31/bd_931e_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_32/bd_931e_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_33/bd_931e_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_34/bd_931e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_35/bd_931e_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_36/bd_931e_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_37/bd_931e_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_38/bd_931e_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_39/bd_931e_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_40/bd_931e_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_41/bd_931e_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_42/bd_931e_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_43/bd_931e_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_44/bd_931e_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_45/bd_931e_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_46/bd_931e_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_47/bd_931e_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_48/bd_931e_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_49/bd_931e_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_50/bd_931e_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_51/bd_931e_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_52/bd_931e_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_53/bd_931e_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_54/bd_931e_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_55/bd_931e_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_56/bd_931e_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_57/bd_931e_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_58/bd_931e_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_59/bd_931e_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_60/bd_931e_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_61/bd_931e_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_62/bd_931e_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_63/bd_931e_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_64/bd_931e_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_65/bd_931e_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_66/bd_931e_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_67/bd_931e_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_68/bd_931e_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_69/bd_931e_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_70/bd_931e_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_71/bd_931e_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_72/bd_931e_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_73/bd_931e_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_74/bd_931e_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_75/bd_931e_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_76/bd_931e_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_1/bd_931e_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_1/bd_931e_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_2/bd_931e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_2/bd_931e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_3/bd_931e_psr_aclk2_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_3/bd_931e_psr_aclk2_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_4/bd_931e_arinsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_5/bd_931e_rinsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_6/bd_931e_awinsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_7/bd_931e_winsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_8/bd_931e_binsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_9/bd_931e_aroutsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_10/bd_931e_routsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_11/bd_931e_awoutsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_12/bd_931e_woutsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_13/bd_931e_boutsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_14/bd_931e_arni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_15/bd_931e_rni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_16/bd_931e_awni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_17/bd_931e_wni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_18/bd_931e_bni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_22/bd_931e_s00a2s_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_23/bd_931e_sarn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_24/bd_931e_srn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_25/bd_931e_sawn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_26/bd_931e_swn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_27/bd_931e_sbn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_28/bd_931e_m00s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_29/bd_931e_m00arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_30/bd_931e_m00rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_31/bd_931e_m00awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_32/bd_931e_m00wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_33/bd_931e_m00bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_35/bd_931e_m01s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_36/bd_931e_m01arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_37/bd_931e_m01rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_38/bd_931e_m01awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_39/bd_931e_m01wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_40/bd_931e_m01bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_42/bd_931e_m02s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_43/bd_931e_m02arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_44/bd_931e_m02rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_45/bd_931e_m02awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_46/bd_931e_m02wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_47/bd_931e_m02bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_49/bd_931e_m03s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_50/bd_931e_m03arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_51/bd_931e_m03rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_52/bd_931e_m03awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_53/bd_931e_m03wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_54/bd_931e_m03bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_56/bd_931e_m04s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_57/bd_931e_m04arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_58/bd_931e_m04rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_59/bd_931e_m04awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_60/bd_931e_m04wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_61/bd_931e_m04bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_63/bd_931e_m05s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_64/bd_931e_m05arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_65/bd_931e_m05rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_66/bd_931e_m05awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_67/bd_931e_m05wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_68/bd_931e_m05bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_70/bd_931e_m06s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_71/bd_931e_m06arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_72/bd_931e_m06rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_73/bd_931e_m06awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_74/bd_931e_m06wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_75/bd_931e_m06bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_icn_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/vitis_design_icn_ctrl_1_0.xci
# IP: The module: 'vitis_design_icn_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/bd_931e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_0/bd_931e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_1/bd_931e_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_2/bd_931e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_3/bd_931e_psr_aclk2_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_4/bd_931e_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_5/bd_931e_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_6/bd_931e_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_7/bd_931e_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_8/bd_931e_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_9/bd_931e_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_10/bd_931e_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_11/bd_931e_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_12/bd_931e_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_13/bd_931e_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_14/bd_931e_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_15/bd_931e_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_16/bd_931e_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_17/bd_931e_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_18/bd_931e_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_19/bd_931e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_20/bd_931e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_21/bd_931e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_22/bd_931e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_23/bd_931e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_24/bd_931e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_25/bd_931e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_26/bd_931e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_27/bd_931e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_28/bd_931e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_29/bd_931e_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_30/bd_931e_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_31/bd_931e_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_32/bd_931e_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_33/bd_931e_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_34/bd_931e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_35/bd_931e_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_36/bd_931e_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_37/bd_931e_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_38/bd_931e_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_39/bd_931e_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_40/bd_931e_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_41/bd_931e_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_42/bd_931e_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_43/bd_931e_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_44/bd_931e_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_45/bd_931e_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_46/bd_931e_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_47/bd_931e_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_48/bd_931e_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_49/bd_931e_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_50/bd_931e_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_51/bd_931e_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_52/bd_931e_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_53/bd_931e_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_54/bd_931e_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_55/bd_931e_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_56/bd_931e_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_57/bd_931e_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_58/bd_931e_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_59/bd_931e_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_60/bd_931e_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_61/bd_931e_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_62/bd_931e_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_63/bd_931e_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_64/bd_931e_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_65/bd_931e_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_66/bd_931e_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_67/bd_931e_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_68/bd_931e_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_69/bd_931e_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_70/bd_931e_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_71/bd_931e_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_72/bd_931e_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_73/bd_931e_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_74/bd_931e_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_75/bd_931e_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_76/bd_931e_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_1/bd_931e_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_1/bd_931e_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_2/bd_931e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_2/bd_931e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_3/bd_931e_psr_aclk2_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_3/bd_931e_psr_aclk2_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_4/bd_931e_arinsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_5/bd_931e_rinsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_6/bd_931e_awinsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_7/bd_931e_winsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_8/bd_931e_binsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_9/bd_931e_aroutsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_10/bd_931e_routsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_11/bd_931e_awoutsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_12/bd_931e_woutsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_13/bd_931e_boutsw_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_14/bd_931e_arni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_15/bd_931e_rni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_16/bd_931e_awni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_17/bd_931e_wni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_18/bd_931e_bni_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_22/bd_931e_s00a2s_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_23/bd_931e_sarn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_24/bd_931e_srn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_25/bd_931e_sawn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_26/bd_931e_swn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_27/bd_931e_sbn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_28/bd_931e_m00s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_29/bd_931e_m00arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_30/bd_931e_m00rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_31/bd_931e_m00awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_32/bd_931e_m00wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_33/bd_931e_m00bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_35/bd_931e_m01s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_36/bd_931e_m01arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_37/bd_931e_m01rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_38/bd_931e_m01awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_39/bd_931e_m01wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_40/bd_931e_m01bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_42/bd_931e_m02s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_43/bd_931e_m02arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_44/bd_931e_m02rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_45/bd_931e_m02awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_46/bd_931e_m02wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_47/bd_931e_m02bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_49/bd_931e_m03s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_50/bd_931e_m03arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_51/bd_931e_m03rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_52/bd_931e_m03awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_53/bd_931e_m03wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_54/bd_931e_m03bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_56/bd_931e_m04s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_57/bd_931e_m04arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_58/bd_931e_m04rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_59/bd_931e_m04awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_60/bd_931e_m04wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_61/bd_931e_m04bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_63/bd_931e_m05s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_64/bd_931e_m05arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_65/bd_931e_m05rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_66/bd_931e_m05awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_67/bd_931e_m05wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_68/bd_931e_m05bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_70/bd_931e_m06s2a_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_71/bd_931e_m06arn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_72/bd_931e_m06rn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_73/bd_931e_m06awn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_74/bd_931e_m06wn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/bd_0/ip/ip_75/bd_931e_m06bn_0_ooc.xdc

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_icn_ctrl_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_icn_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
