# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0.xci
# IP: The module: 'vitis_design_noc_lpddr4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/bd_28ba.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba || ORIG_REF_NAME==bd_28ba} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_0/bd_28ba_MC1_ddrc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba_MC1_ddrc_0 || ORIG_REF_NAME==bd_28ba_MC1_ddrc_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_0/ip_0/bd_28ba_MC1_ddrc_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba_MC1_ddrc_0_phy || ORIG_REF_NAME==bd_28ba_MC1_ddrc_0_phy} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_1/bd_28ba_MC0_ddrc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba_MC0_ddrc_0 || ORIG_REF_NAME==bd_28ba_MC0_ddrc_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_1/ip_0/bd_28ba_MC0_ddrc_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_28ba_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_0/hdl/par/bd_28ba_MC1_ddrc_0_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28ba_MC1_ddrc_0 || ORIG_REF_NAME==bd_28ba_MC1_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_1/hdl/par/bd_28ba_MC0_ddrc_0_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28ba_MC0_ddrc_0 || ORIG_REF_NAME==bd_28ba_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_noc_lpddr4_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_noc_lpddr4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_noc_lpddr4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0.xci
# IP: The module: 'vitis_design_noc_lpddr4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/bd_28ba.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba || ORIG_REF_NAME==bd_28ba} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_0/bd_28ba_MC1_ddrc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba_MC1_ddrc_0 || ORIG_REF_NAME==bd_28ba_MC1_ddrc_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_0/ip_0/bd_28ba_MC1_ddrc_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba_MC1_ddrc_0_phy || ORIG_REF_NAME==bd_28ba_MC1_ddrc_0_phy} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_1/bd_28ba_MC0_ddrc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba_MC0_ddrc_0 || ORIG_REF_NAME==bd_28ba_MC0_ddrc_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_1/ip_0/bd_28ba_MC0_ddrc_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_28ba_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_28ba_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_0/hdl/par/bd_28ba_MC1_ddrc_0_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28ba_MC1_ddrc_0 || ORIG_REF_NAME==bd_28ba_MC1_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/bd_0/ip/ip_1/hdl/par/bd_28ba_MC0_ddrc_0_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28ba_MC0_ddrc_0 || ORIG_REF_NAME==bd_28ba_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_noc_lpddr4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_noc_lpddr4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_noc_lpddr4_0/vitis_design_noc_lpddr4_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_noc_lpddr4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
