# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0.xci
# IP: The module: 'vitis_design_cips_noc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/bd_27ec.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec || ORIG_REF_NAME==bd_27ec} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_0/bd_27ec_S07_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S07_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_1/bd_27ec_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_const_0_0 || ORIG_REF_NAME==bd_27ec_const_0_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_2/bd_27ec_S04_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S04_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S04_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_3/bd_27ec_S03_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S03_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_4/bd_27ec_S06_AXI_rpu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S06_AXI_rpu_0 || ORIG_REF_NAME==bd_27ec_S06_AXI_rpu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_5/bd_27ec_S02_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S02_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_6/bd_27ec_S05_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S05_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_7/bd_27ec_S01_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_8/bd_27ec_S00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_9/bd_27ec_M00_AXI_nsu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_27ec_M00_AXI_nsu_0} -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_0/xdc/bd_27ec_S07_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S07_AXI_nmu_0} -quiet] {/bd_27ec_S07_AXI_nmu_0_top_INST } ]/bd_27ec_S07_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_2/xdc/bd_27ec_S04_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S04_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S04_AXI_nmu_0} -quiet] {/bd_27ec_S04_AXI_nmu_0_top_INST } ]/bd_27ec_S04_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_3/xdc/bd_27ec_S03_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S03_AXI_nmu_0} -quiet] {/bd_27ec_S03_AXI_nmu_0_top_INST } ]/bd_27ec_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_4/xdc/bd_27ec_S06_AXI_rpu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S06_AXI_rpu_0 || ORIG_REF_NAME==bd_27ec_S06_AXI_rpu_0} -quiet] {/bd_27ec_S06_AXI_rpu_0_top_INST } ]/bd_27ec_S06_AXI_rpu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_5/xdc/bd_27ec_S02_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S02_AXI_nmu_0} -quiet] {/bd_27ec_S02_AXI_nmu_0_top_INST } ]/bd_27ec_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_6/xdc/bd_27ec_S05_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S05_AXI_nmu_0} -quiet] {/bd_27ec_S05_AXI_nmu_0_top_INST } ]/bd_27ec_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_7/xdc/bd_27ec_S01_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S01_AXI_nmu_0} -quiet] {/bd_27ec_S01_AXI_nmu_0_top_INST } ]/bd_27ec_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_8/xdc/bd_27ec_S00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S00_AXI_nmu_0} -quiet] {/bd_27ec_S00_AXI_nmu_0_top_INST } ]/bd_27ec_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_9/xdc/bd_27ec_M00_AXI_nsu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_27ec_M00_AXI_nsu_0} -quiet] {/bd_27ec_M00_AXI_nsu_0_top_INST } ]/bd_27ec_M00_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_cips_noc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_cips_noc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_cips_noc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0.xci
# IP: The module: 'vitis_design_cips_noc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/bd_27ec.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec || ORIG_REF_NAME==bd_27ec} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_0/bd_27ec_S07_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S07_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_1/bd_27ec_const_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_const_0_0 || ORIG_REF_NAME==bd_27ec_const_0_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_2/bd_27ec_S04_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S04_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S04_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_3/bd_27ec_S03_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S03_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_4/bd_27ec_S06_AXI_rpu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S06_AXI_rpu_0 || ORIG_REF_NAME==bd_27ec_S06_AXI_rpu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_5/bd_27ec_S02_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S02_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_6/bd_27ec_S05_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S05_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_7/bd_27ec_S01_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_8/bd_27ec_S00_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_9/bd_27ec_M00_AXI_nsu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_27ec_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_27ec_M00_AXI_nsu_0} -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_0/xdc/bd_27ec_S07_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S07_AXI_nmu_0} -quiet] {/bd_27ec_S07_AXI_nmu_0_top_INST } ]/bd_27ec_S07_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_2/xdc/bd_27ec_S04_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S04_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S04_AXI_nmu_0} -quiet] {/bd_27ec_S04_AXI_nmu_0_top_INST } ]/bd_27ec_S04_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_3/xdc/bd_27ec_S03_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S03_AXI_nmu_0} -quiet] {/bd_27ec_S03_AXI_nmu_0_top_INST } ]/bd_27ec_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_4/xdc/bd_27ec_S06_AXI_rpu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S06_AXI_rpu_0 || ORIG_REF_NAME==bd_27ec_S06_AXI_rpu_0} -quiet] {/bd_27ec_S06_AXI_rpu_0_top_INST } ]/bd_27ec_S06_AXI_rpu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_5/xdc/bd_27ec_S02_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S02_AXI_nmu_0} -quiet] {/bd_27ec_S02_AXI_nmu_0_top_INST } ]/bd_27ec_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_6/xdc/bd_27ec_S05_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S05_AXI_nmu_0} -quiet] {/bd_27ec_S05_AXI_nmu_0_top_INST } ]/bd_27ec_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_7/xdc/bd_27ec_S01_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S01_AXI_nmu_0} -quiet] {/bd_27ec_S01_AXI_nmu_0_top_INST } ]/bd_27ec_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_8/xdc/bd_27ec_S00_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_27ec_S00_AXI_nmu_0} -quiet] {/bd_27ec_S00_AXI_nmu_0_top_INST } ]/bd_27ec_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/bd_0/ip/ip_9/xdc/bd_27ec_M00_AXI_nsu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_27ec_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_27ec_M00_AXI_nsu_0} -quiet] {/bd_27ec_M00_AXI_nsu_0_top_INST } ]/bd_27ec_M00_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_cips_noc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_cips_noc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Desktop/dsp_recon/system_project/mac/mac/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_cips_noc_0/vitis_design_cips_noc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vitis_design_cips_noc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
